import axios from 'axios';
import { HackerNewsResponse, HackerNewsItem, FetchResult, ItemInsert } from '../../types/index.js';
import { logger } from '../logger.js';

const HN_API_BASE = 'https://hn.algolia.com/api/v1';

// AI-related search queries
const AI_QUERIES = [
  'artificial intelligence',
  'machine learning',
  'LLM',
  'GPT',
  'Claude',
  'Gemini',
  'AI tool',
  'neural network',
  'deep learning',
  'OpenAI',
  'Anthropic'
];

export async function fetchHackerNews(): Promise<FetchResult> {
  try {
    logger.info('Fetching Hacker News...');
    
    const items: ItemInsert[] = [];
    const seenUrls = new Set<string>();
    
    // Fetch recent stories with AI-related tags
    const searchQuery = AI_QUERIES.slice(0, 3).join(' OR ');
    
    const response = await axios.get<HackerNewsResponse>(`${HN_API_BASE}/search`, {
      params: {
        query: searchQuery,
        tags: 'story',
        hitsPerPage: 30,
        numericFilters: `created_at_i>${Math.floor(Date.now() / 1000) - 86400 * 2}` // Last 2 days
      }
    });
    
    for (const hit of response.data.hits) {
      const url = hit.url || `https://news.ycombinator.com/item?id=${hit.objectID}`;
      
      if (seenUrls.has(url)) continue;
      seenUrls.add(url);
      
      items.push({
        source: 'hackernews',
        url,
        url_hash: '', // Will be generated by database
        title: hit.title,
        raw_text: hit.story_text || hit.title,
        author: hit.author,
        processed: false
      });
    }
    
    // Also fetch front page for high-signal items
    const frontPageResponse = await axios.get<HackerNewsResponse>(`${HN_API_BASE}/search`, {
      params: {
        tags: 'front_page',
        hitsPerPage: 20
      }
    });
    
    // Filter front page for AI-related content
    const aiKeywords = ['ai', 'ml', 'llm', 'gpt', 'claude', 'model', 'neural', 'learning', 'openai', 'anthropic'];
    
    for (const hit of frontPageResponse.data.hits) {
      const titleLower = hit.title.toLowerCase();
      const isAIRelated = aiKeywords.some(kw => titleLower.includes(kw));
      
      if (!isAIRelated) continue;
      
      const url = hit.url || `https://news.ycombinator.com/item?id=${hit.objectID}`;
      
      if (seenUrls.has(url)) continue;
      seenUrls.add(url);
      
      items.push({
        source: 'hackernews',
        url,
        url_hash: '',
        title: hit.title,
        raw_text: hit.story_text || hit.title,
        author: hit.author,
        processed: false
      });
    }
    
    logger.info(`Fetched ${items.length} items from Hacker News`);
    
    return {
      source: 'hackernews',
      items
    };
  } catch (error) {
    logger.error('Error fetching Hacker News:', error);
    return {
      source: 'hackernews',
      items: [],
      error: error instanceof Error ? error.message : 'Unknown error'
    };
  }
}
