import Parser from 'rss-parser';
import { logger } from '../logger.js';
import { FetchResult, ItemInsert } from '../../types/index.js';

const parser = new Parser({
  timeout: 10000,
  headers: {
    'User-Agent': 'ZappNews/1.0 AI News Aggregator'
  }
});

// Popular AI/Tech RSS feeds - add more as needed!
const RSS_FEEDS: { url: string; name: string; category: string }[] = [
  // AI Company Blogs
  { url: 'https://openai.com/blog/rss/', name: 'OpenAI Blog', category: 'ai_company' },
  { url: 'https://www.anthropic.com/rss.xml', name: 'Anthropic', category: 'ai_company' },
  { url: 'https://blog.google/technology/ai/rss/', name: 'Google AI Blog', category: 'ai_company' },
  { url: 'https://ai.meta.com/blog/rss/', name: 'Meta AI', category: 'ai_company' },
  
  // Tech News
  { url: 'https://techcrunch.com/category/artificial-intelligence/feed/', name: 'TechCrunch AI', category: 'tech_news' },
  { url: 'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml', name: 'The Verge AI', category: 'tech_news' },
  { url: 'https://www.wired.com/feed/tag/ai/latest/rss', name: 'Wired AI', category: 'tech_news' },
  { url: 'https://venturebeat.com/category/ai/feed/', name: 'VentureBeat AI', category: 'tech_news' },
  
  // Research & Academic
  { url: 'https://bair.berkeley.edu/blog/feed.xml', name: 'Berkeley AI Research', category: 'research' },
  { url: 'https://ai.googleblog.com/feeds/posts/default', name: 'Google AI Research', category: 'research' },
  
  // Developer & Tools
  { url: 'https://huggingface.co/blog/feed.xml', name: 'Hugging Face', category: 'developer' },
  { url: 'https://www.langchain.com/blog/rss.xml', name: 'LangChain', category: 'developer' },
  
  // Newsletters (if they have RSS)
  { url: 'https://bensbites.beehiiv.com/feed', name: "Ben's Bites", category: 'newsletter' },
  { url: 'https://www.deeplearning.ai/the-batch/feed/', name: 'The Batch (DeepLearning.AI)', category: 'newsletter' },
];

export async function fetchRSSFeeds(): Promise<FetchResult> {
  const items: ItemInsert[] = [];
  const errors: string[] = [];
  
  logger.info(`Fetching from ${RSS_FEEDS.length} RSS feeds...`);
  
  // Fetch all feeds in parallel
  const results = await Promise.allSettled(
    RSS_FEEDS.map(async (feed) => {
      try {
        const parsed = await parser.parseURL(feed.url);
        const feedItems: ItemInsert[] = (parsed.items || []).slice(0, 5).map(item => ({
          source: 'rss' as const,
          url: item.link || '',
          url_hash: '', // Will be generated by database
          title: item.title || 'Untitled',
          raw_text: item.contentSnippet || item.content || item.summary || item.title || '',
          author: item.creator || item.author || feed.name,
          processed: false
        }));
        return { feed: feed.name, items: feedItems, success: true as const };
      } catch (error) {
        return { feed: feed.name, error: String(error), success: false as const };
      }
    })
  );
  
  // Process results
  for (const result of results) {
    if (result.status === 'fulfilled') {
      if (result.value.success && result.value.items) {
        items.push(...result.value.items);
        logger.info(`Fetched ${result.value.items.length} items from ${result.value.feed}`);
      } else if (!result.value.success) {
        errors.push(`${result.value.feed}: ${result.value.error}`);
        logger.warn(`Failed to fetch ${result.value.feed}: ${result.value.error}`);
      }
    }
  }
  
  logger.info(`RSS: Fetched ${items.length} total items from ${RSS_FEEDS.length - errors.length} feeds`);
  
  return {
    source: 'rss',
    items,
    errors: errors.length > 0 ? errors : undefined
  };
}

// Allow adding custom feeds at runtime
export function addCustomFeed(url: string, name: string, category: string = 'custom') {
  RSS_FEEDS.push({ url, name, category });
  logger.info(`Added custom RSS feed: ${name}`);
}

export function listFeeds() {
  return RSS_FEEDS.map(f => ({ name: f.name, url: f.url, category: f.category }));
}
